#!/usr/bin/env bash
# Prepares the local test after `docker compose up`: throwaway secrets (test/.work/vault.yml, never
# real ones) and the S3 buckets that Terraform creates in AWS, created here in Floci.
set -euo pipefail
cd "$(dirname "$0")"

FLOCI="${TT_TEST_FLOCI:-http://127.0.0.1:34566}"
WORK=.work
mkdir -p "$WORK"
umask 077

if [ ! -s "$WORK/vault.yml" ]; then
  openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "$WORK/jwt-privada.pem" 2>/dev/null
  openssl pkey -in "$WORK/jwt-privada.pem" -pubout -out "$WORK/jwt-publica.pem"
  {
    echo "# Throwaway values for the local test host only. Generated by test/prepare.sh."
    echo "vault_postgres_password: \"$(openssl rand -hex 16)\""
    echo "vault_mediamtx_auth_secret: \"$(openssl rand -hex 32)\""
    echo "vault_fcm_credentials_json: \"\""
    echo "vault_registry_password: \"\""
    echo "vault_jwt_private_key_pem: |"
    sed 's/^/  /' "$WORK/jwt-privada.pem"
    echo "vault_jwt_public_key_pem: |"
    sed 's/^/  /' "$WORK/jwt-publica.pem"
  } > "$WORK/vault.yml"
  rm -f "$WORK/jwt-privada.pem" "$WORK/jwt-publica.pem"
  echo "Wrote throwaway secrets to test/$WORK/vault.yml"
fi

# Buckets (signed with Floci's built-in test/test keys; Floci verifies signatures).
for bucket in te-tengo-clips te-tengo-backups; do
  code=$(curl -sS -o /dev/null -w '%{http_code}' --aws-sigv4 "aws:amz:us-east-1:s3" --user test:test \
    -X PUT "$FLOCI/$bucket")
  case "$code" in
    200|409) echo "Bucket $bucket ready in Floci" ;;
    *) echo "Could not create bucket $bucket in Floci (HTTP $code)" >&2; exit 1 ;;
  esac
done
