---
- name: Reload caddy
  ansible.builtin.command:
    cmd: docker compose exec -T caddy caddy reload --config /etc/caddy/Caddyfile --adapter caddyfile
    chdir: "{{ app_dir }}"
  changed_when: true
  when: app_stack_existed | default(false)

- name: Restart mediamtx
  ansible.builtin.command:
    cmd: docker compose restart mediamtx
    chdir: "{{ app_dir }}"
  changed_when: true
  when: app_stack_existed | default(false)

- name: Restart api
  ansible.builtin.command:
    cmd: docker compose restart api
    chdir: "{{ app_dir }}"
  changed_when: true
  when: app_stack_existed | default(false)
